#!/usr/bin/env bash

set -euo pipefail

##
# meant to be run in vagrant vm
##

SCRIPT_DIR="$(dirname $0)"
DESTINATION="/vagrant/vagrant/packages"
VERSION="0.3.0"
MIRROR="http://mirror.metrocast.net/apache/nifi/nifi-registry/nifi-registry-${VERSION}"
PACKAGE="nifi-registry-${VERSION}-bin.tar.gz"
PACKAGE_SHA256="4e432b6436881d641c45595cb98f7f6f3c396ca28dd85ce51c7b66c9b2bf8710"

${SCRIPT_DIR}/download-package -d "${DESTINATION}" -p "${PACKAGE}" -u "${MIRROR}/${PACKAGE}"

PACKAGE_PATH="${DESTINATION}/${PACKAGE}"
INSTALL_PATH="/opt"

# compare
DOWNLOADED_SHA256=`sha256sum "${PACKAGE_PATH}" | cut -d ' ' -f 1`
NIFI_DIR="/opt/nifi-registry-${VERSION}"

if [ "${PACKAGE_SHA256}" = "${DOWNLOADED_SHA256}" ]; then
  echo "Checksum is valid"
  echo "Installing ${PACKAGE}..."
  mkdir -p "${NIFI_DIR}"
  tar -C "${INSTALL_PATH}" -xzf "${PACKAGE_PATH}"
  ${NIFI_DIR}/bin/nifi-registry.sh install
  systemctl daemon-reload
else
  echo "Checksums don't match: Expected: ${PACKAGE_SHA256}, Actual: ${DOWNLOADED_SHA256}"
  exit 1
fi
